// generated by Fast Light User Interface Designer (fluid) version 1.0011

#ifndef digital_h
#define digital_h
#include <FL/Fl.H>
void time_CB(Fl_Widget*, void*);
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
extern Fl_Box *Box_Empty;
extern Fl_Box *BOX_0;
extern Fl_Box *BOX_1;
extern Fl_Box *BOX_2;
extern Fl_Box *BOX_3;
extern Fl_Box *BOX_4;
extern Fl_Box *BOX_5;
extern Fl_Box *BOX_6;
extern Fl_Box *BOX_7;
extern Fl_Box *BOX_8;
extern Fl_Box *BOX_9;
extern Fl_Box *BOX_temp;
Fl_Window* main();
#endif
