//generated by FLTK 1.1.4 (dev-c++ 4.9.9.2)
#include "SubFltk.h"
#include <FL/fl_ask.h> // fl_message 함수 사용시 필요함. 
#include <windows.h>   // MessageBox 함수 사용시 필요함. 
static HWND hWnd;


void Button_CB(Fl_Widget *, void *) {
     fl_message("Button Callback!");
     //MessageBox(hWnd, "Button Callback!","test",MB_OK);
}
      

int main (int argc, char ** argv)
{
/*    
  Fl_Window *window;
  Fl_Box *box;

  window = new Fl_Window (300, 180);
  box = new Fl_Box (20, 40, 260, 100, "Hello World!");

  box->box (FL_UP_BOX);
  box->labelsize (36);
  box->labelfont (FL_BOLD+FL_ITALIC);
  box->labeltype (FL_SHADOW_LABEL);
  window->end ();
  window->show (argc, argv);
*/
  Fl_Double_Window* w;
  {
    Fl_Double_Window* o = new Fl_Double_Window(380, 256);
    w = o;
    {
        Fl_Button * o = new Fl_Button(100, 80, 190, 30, "button");
        o->callback((Fl_Callback*)Button_CB);  
    }
    o->end();
  }
  w->show(argc, argv);
  return(Fl::run());
}
