//generated by FLTK 1.1.4 (dev-c++ 4.9.9.2)
#ifndef SUBFLTK_H
#define SUBFLTK_H
#include <FL/Fl.H>
void Button_CB(Fl_Widget *, void *); //버튼 콜백 함수 
#include <FL/Fl_Double_Window.H> //윈도우 생성시 필요함.
#include <FL/Fl_Button.H> // 버튼 사용시 필요함. 
#endif 
